repos:
- repo: local
  hooks:
    - id: check_headers
      name: Run headers check
      description: Check for copyright and license headers in .py files
      entry: bash
      args: ["./scripts/check_headers.sh"]
      language: system
      pass_filenames: false
    - id: bandit 
      name: Run Bandit Linter
      entry: bash 
      args: ["./scripts/bandit.sh"]
      language: system
      pass_filenames: false
    - id: linter
      name: Run linter
      entry: bash
      args: ["./scripts/linter.sh"]
      language: system
      pass_filenames: false
    - id: check_format
      name: Run black code formatter
      entry: bash 
      args: ["./scripts/check_format.sh"]
      language: system
      pass_filenames: false
    - id: check_type
      name: Run type checker
      entry: bash 
      args: ["./scripts/check_type.sh"]
      language: system
      pass_filenames: false
