# nodes:
# - input.visual:
#     # source: https://storage.googleapis.com/peekingduck/videos/wave.mp4
#     #source: ../coco/images/val2017/000000000139.jpg 
#     # source: ../custom_images/cars_crowd.jpeg
#     #source: ../coco/images/val2017/000000002299.jpg
#     #source: ../custom_images/cte_traffic_orchard_zoom_1_TRIMMED.MOV
#     source: ../custom_images/a_lot_of_cars.mp4
# - model.yolov6: # yolov6 yolox
#     model_type: "yolov6t"
#     detect_ids: ["*"] # ["person"]]
#     input_size: 416
#     iou_threshold: 0.25     # default 0.25
#     score_threshold: 0.2  # default 0.45
#     agnostic_nms: true
#     half: false
#     fuse: true
#     multi_label: false
#     max_detections: 300
# # - model.yolox: 
# #     model_type: "yolox-tiny"
# #     detect_ids: ["*"]
# #     input_size: 416
# #     iou_threshold: 0.25
# #     score_threshold: 0.2
# #     agnostic_nms: true
# #     half: false
# #     fuse: true
# - dabble.fps
# - draw.legend:
#     show: ["fps", "filename"]
# - draw.bbox:
#     show_labels: True
# - output.screen
# - output.media_writer
# - output.csv_writer:
#     stats_to_track: ["bbox_labels", "bbox_scores"]
#     logging_interval: 0


# Get groundtruths for tests
# nodes:
# - input.visual:
#     #source: ./tests/data/images/t1.jpg
#     #source: ./tests/data/images/t2.jpg
#     source: ./tests/data/images/t4.jpg
# - model.yolov6: # yolov6 yolox
#     model_type: "yolov6n"
#     # detect_ids: [0] # ["person"]]
#     # input_size: 640
#     # iou_threshold: 0.45     # default 0.45
#     # score_threshold: 0.25  # default 0.25
#     # agnostic_nms: true
#     # half: false
#     # fuse: true
#     # multi_label: true
#     # max_detections: 300
# - dabble.fps
# - draw.legend:
#     show: ["fps", "filename"]
# - draw.bbox:
#     show_labels: True
# - output.screen
# - output.media_writer
# - output.csv_writer:
#     stats_to_track: ["bbox_labels", "bbox_scores"]
#     logging_interval: 0


######## COCO specific image to check tensors - the one Yier recommended ######
nodes:
- input.visual:
    source: ../coco/images/val2017/000000000139.jpg 
- model.yolov6: # yolov6 yolox
    detect_ids: ["*"] # ["person"]]
    # model_type: "yolov6n"
    # input_size: 640
    # iou_threshold: 0.45     # default 0.25
    # score_threshold: 0.25  # default 0.45
    # agnostic_nms: true
    # half: false
    # fuse: true
    # multi_label: true
    # max_detections: 300
- dabble.fps
- draw.legend:
    show: ["fps", "filename"]
- draw.bbox:
    show_labels: True
- output.screen
- output.media_writer
- output.csv_writer:
    stats_to_track: ["bbox_labels", "bbox_scores"]
    logging_interval: 0

############## PKD default config ################
# nodes:
# - input.visual:
#     source: https://storage.googleapis.com/peekingduck/videos/wave.mp4
# - model.posenet
# - draw.poses
# - output.screen