input: ["keypoints", "keypoint_scores", "keypoint_conns", "img"]
output: ["none"]
callbacks: {}

keypoint_dot_color: tomato # [77, 103, 255]
keypoint_connect_color: champagne # [156, 223, 244]
keypoint_dot_radius: 5
